### ISSUE TITLE
Filtered posts design

### ISSUE THREAD

**Issue by leesus** [poultonjoe/Mandragora#10]
@poultonjoe

**Comment by poultonjoe** [comment]
Selected filtered posts should be reversed out. Unselected - white background with colour text as is atm. Selected - colour background with white text. Can we also stack is underneath the search bar and have it max width of lets say 60% of the hero-intro window width. Reason being that the thinking face (face3) from the services page will now be on the blog section. I'm going to draw a new face for the contact section (a winking face) and move the existing one (face2) to the homepage, and move the homepage face (face1) to the services page.

**Comment by leesus** [comment]
@poultonjoe After our conversation earlier, can this be closed off now?

**Comment by poultonjoe** [comment]
Yes, no need for filtering.
