### ISSUE TITLE
Rearrange Avatars

### ISSUE THREAD

**Issue by poultonjoe** [poultonjoe/Mandragora#11]
Thinking face (face3) from the services page will now be on the blog section in the position of the other pages on the first post/hero only. New face attached for the contact section (a winking face) and move the existing one (face2) to the homepage, and move the homepage face (face1) to the services page.
[face6_new_contact.zip](https://github.com/poultonjoe/Mandragora/files/369131/face6_new_contact.zip)

**Comment by leesus** [comment]
@poultonjoe This is all done except for the blog. I've added it, but unsure how you want it to display, please advise.

**Comment by poultonjoe** [comment]
![blog_revision](https://cloud.githubusercontent.com/assets/7655069/16934501/66cf5be6-4d89-11e6-87ad-bf2e0f0c5ca2.gif)

**Comment by poultonjoe** [comment]
Drop the filters altogether, move down the face so the padding between menu and avatar is consistent, as well as the positioning/indentation from the right of the hero-intro section
