### ISSUE TITLE
Contact Form Drop Down Options:

### ISSUE THREAD

**Issue by poultonjoe** [poultonjoe/Mandragora#14]
The drop down options for the contact form should be:

**Type of work:**

o   Certified translation

o   Standard translation

o   I’m not sure/other – please state in your enquiry

**Preferred delivery date**

o   Calendar pop up or dd/mm/yyyy rule

**Delivery Method** instead of collection method.

o   Email

o   In person

o   By post (address fields pop up if this option selected)

**Comment by leesus** [comment]
What are the postal fields for singapore?

**Comment by poultonjoe** [comment]
No minimum time really but let's put it as next day being the earliest option - can be charged as a rush job if short notice I suppose.

Fields can be as below to cater for any address.

Address Line 1
Address Line 2
Address Line 3
Country
Postal Code
