### ISSUE TITLE
Update contact form email template

### ISSUE THREAD

**Issue by leesus** [poultonjoe/Mandragora#16]
Needs to go to correct personal email address when set up instead of mine.

@poultonjoe need an 'admin@mandragoratranslations.com' or similar email account setting up that forwards to her personal email address (so users can't see it but can still reply).

**Comment by poultonjoe** [comment]
I set up 'hello@mandragoratranslations.com'. It forwards to her personal e-mail 'haizea@man...'

**Comment by leesus** [comment]
Ok cool, will swap it over. Do you have access to the haizea@... mailbox so you can test the email template ok etc?

**Comment by poultonjoe** [comment]
Yes, can get it but I'd better let her know first

**Comment by leesus** [comment]
I'll have it send to you for now, once it's ok can change over.

**Comment by poultonjoe** [comment]
No prob
