### ISSUE TITLE
Add full list of countries to dropdown

### ISSUE THREAD

**Issue by leesus** [poultonjoe/Mandragora#17]
@poultonjoe It currently has US, UK and Spain. Assume will need more, but do we need every single country of the world in there or just a handful of markets she works with?

**Comment by poultonjoe** [comment]
Can we shift to regions? I Think this will work best after chatting.

·         Singapore

·         Malaysia

·         Rest of South East Asia, Hong Kong, Taiwan, Macau

·         Rest of Asia, Australia, New Zealand

·         Europe, USA, Canada, Mexico

·         Rest of the World

**Comment by leesus** [comment]
Only issue with that is it is a postal address form. So doesn't really make sense.

**Comment by poultonjoe** [comment]
Can we just put country as free text then?

I get this pop up even after everything is filled out (top left)
![screen shot 2016-08-09 at 4 52 12 pm](https://cloud.githubusercontent.com/assets/7655069/17510547/fb90c656-5e51-11e6-9c1f-3bc70e55fa37.png)
