### ISSUE TITLE
Sticky Menu Opacity

### ISSUE THREAD

**Issue by poultonjoe** [poultonjoe/Mandragora#2]
On page load the menu looks as if it's 50% rather than 25% opacity. When you scroll down you can see the shift and both the menu and background become the same opacity. It looks as if when scrolled all the way to the top the two are stacked and it's 25% + 25%. Would a way around this be to use a non transparent svg/img with a blue background? Just a thought. Screenshot attached - this is in safari, chrome & firefox. IE not tested.
![screen shot 2016-07-14 at 11 03 04 pm](https://cloud.githubusercontent.com/assets/7655069/16844450/c8dbe2fc-4a17-11e6-9ff1-64789b5b7cb4.png)
![screen shot 2016-07-14 at 11 02 47 pm](https://cloud.githubusercontent.com/assets/7655069/16844451/c8e2afc4-4a17-11e6-9379-71997a95686f.png)

**Comment by leesus** [comment]
Fixed
