### ISSUE TITLE
Search results design

### ISSUE THREAD

**Issue by leesus** [poultonjoe/Mandragora#9]
@poultonjoe

**Comment by poultonjoe** [comment]
Search results to look like the blog post but without showing the featured image and only showing the title, author, date, category (maybe not) and first 200 char with a read more link below. Also listed in individual boxes almost like lots of hero-intro's or when the blog section stacks on top of itself.
![screen shot 2016-07-18 at 9 40 17 pm](https://cloud.githubusercontent.com/assets/7655069/16916701/c699281c-4d30-11e6-8204-c00958aed842.png)
![screen shot 2016-07-18 at 9 44 01 pm](https://cloud.githubusercontent.com/assets/7655069/16916702/ca0c77ec-4d30-11e6-8215-ceed21d6fc3e.png)

**Comment by leesus** [comment]
Will implement in wordpress rather than create a page for it.
